name: Deploy Backend via SSH

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Copiar arquivos para o servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/var/www/leonilso-api"

      - name: Executar deploy remoto
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/leonilso-api

            mkdir -p data

            docker build -t leonilso-backend .

            docker stop leonilso-backend || true
            docker rm leonilso-backend || true

            docker run -d \
              -p 3001:3001 \
              -v /var/www/leonilso-api/data:/app \
              --restart always \
              --name leonilso-backend \
              leonilso-backend